### ISSUE TITLE
Weekend Topic

### ISSUE THREAD

**Issue by ashokkondapalli** [ashokkondapalli/MSIT_DADV_16#2]
@anirudh708, we want to discuss on Neural networks on this saturday

**Comment by wanirudh** [comment]
[this](https://www.youtube.com/playlist?list=PLgcwDw9tMf6gmk0kTvAE0FlZs1S09zJnE) shall make understanding simple.

**Comment by venkatesh-venky** [comment]
bro are you coming tomorrow?
